DATAS SEGMENT
	DATA1 DB 00H,02H,10H,04H
	DATA2 DB ?
    ;此处输入数据段代码  
DATAS ENDS

CODES SEGMENT
    ASSUME CS:CODES,DS:DATAS
START:	MOV AX,DATAS
	    MOV DS,AX
	    MOV BX,00H
	    LEA CX,DATA2
	    INC CX
LOOP3:		MOV AH,[BX]
		AND AH,0EH
		MOV [BX],AH
		INC BX
		LOOP LOOP3
SORT:	LEA CX,DATA2
		DEC CX
LOOP1:	MOV DX,CX
		MOV BX,0
LOOP2:	MOV AX,[BX]
		CMP AX,[BX+1]
		JAE NO_CHANGE
		XCHG AX,[BX+1]
		MOV [BX],AX
NO_CHANGE:
		ADD BX,1
		LOOP LOOP2
		MOV CX,DX
		LOOP LOOP1
	;开始统计相等个数
		LEA CX,DATA2
		DEC CX
		MOV BX,0
		MOV AL,1
LOOP4:	MOV AH,[BX]
		CMP AH,[BX+1]
		JNE NEXT
		INC AL
NEXT:	INC BX
		LOOP LOOP4
		MOV AH,4CH
    	INT 21H
CODES ENDS
    END START
